-- STATUS_TYPE Table --
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STATUS_TYPE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
  	DBMS_OUTPUT.PUT_LINE('Table Not Found');
END;
new-line

CREATE TABLE STATUS_TYPE (
	ID NUMBER NOT NULL,
	STATUS_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);
new-line

-- TODO Table & TODO_SEQ Seqeunce --
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TODO CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
  	DBMS_OUTPUT.PUT_LINE('Table Not Found');
END;
new-line

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE TODO_SEQ';
EXCEPTION
  WHEN OTHERS THEN
  	DBMS_OUTPUT.PUT_LINE('Sequence Not Found');
END;
new-line

CREATE SEQUENCE TODO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE ORDER;
new-line

CREATE TABLE TODO (
	ID NUMBER NOT NULL,
	STATUS_ID NUMBER,
	ITEM VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);
new-line

ALTER TABLE TODO ADD CONSTRAINT FK_TODO_STATUS_ID
foreign KEY(STATUS_ID) references STATUS_TYPE (ID);
new-line

-- TODO_VIEW --
CREATE OR REPLACE VIEW TODO_VIEW 
AS
  SELECT TODO.ID AS ID,
				 STATUS_TYPE.STATUS_NAME as STATUS_NAME,
				 TODO.ITEM AS ITEM
  FROM TODO
  INNER JOIN STATUS_TYPE
  ON TODO.STATUS_ID = STATUS_TYPE.ID;
new-line

-- TODO_LENGTH_VIEW --
CREATE OR REPLACE VIEW TODO_LENGTH_VIEW 
AS
  SELECT ID,
				 LENGTH(ITEM) as ITEM_LENGTH
  FROM TODO;
new-line